# Site settings
title: Daniel Christodoulopoulos
name: Daniel Christodoulopoulos
description: "Welcome...<br> I'm Daniel Christodoulopoulos and i live in Athens Greece. I graduated from school of Electrical and Computer Engineering of National Technical Uninversity of Athens.<br>You can check my links below. Feel free to contact me."
url: "https://danchris.github.io"

github_username:  danchris
facebook_username: daniel.christodoulopoulos
#instagram_username:  danchris__
email: danielchristodoulopoulos@gmail.com
linkedin_username: daniel-christodoulopoulos

avatar: yes
avatar_img_path: "imgs/daniel.jpg"

favicon: yes
favicon_img_path: "favicon.ico"

#front_img: no
#front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

include: [.well-known]
