# Site settings
title: Daniel Christodoulopoulos
name: Daniel Christodoulopoulos
description: "Hey! I'm Daniel Christodoulopoulos and i live in Athens Greece. I'm undergraduate student at school of Electrical and Computer Engineering of National Technical Uninversity of Athens."
url: "https://danchris.github.io"

github_username:  danchris
facebook_username: daniel.christodoulopoulos
instagram_username:  danchris__
email: danielchristodoulopoulos@gmail.com
#linkedin_username: your_linked_in_username_goes_here

avatar: yes
avatar_img_path: "imgs/daniel.jpg"

favicon: yes
favicon_img_path: "favicon.ico"

front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty
